version: 2

# https://docs.getdbt.com/docs/building-a-dbt-project/tests

models:
  - name: stg_addresses
    columns:
      - name: address_id
        tests:
          - unique
          - not_null
      - name: address
      - name: zipcode
        tests:
          - max_five_digit_zipcode
      - name: state
      - name: country
        tests:
          - country_is_united_states

  - name: stg_events 
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: session_id
      - name: user_id
        tests:
          - relationships:
              to: ref('stg_users')
              field: user_id
      - name: page_url
      - name: created_at
      - name: event_type
        tests:
          - accepted_values:
              values: ['add_to_cart', 'checkout', 'page_view', 'package_shipped']
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        tests:
          - relationships:
              to: ref('stg_products')
              field: product_id

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: promo_id
        tests:
          - relationships:
              to: ref('stg_promos')
              field: promo_id
      - name: user_id
        tests:
          - relationships:
              to: ref('stg_users')
              field: user_id
      - name: address_id
        tests:
          - relationships:
              to: ref('stg_addresses')
              field: address_id
      - name: created_at
      - name: order_cost
        tests: 
          - positive_values
      - name: shipping_cost
        tests:
          - positive_values
      - name: order_total
        tests:
          - positive_values
      - name: tracking_id
      - name: shipping_service
        tests:
          - accepted_values:
              values: ['fedex', 'dhl', 'ups', 'usps']
      - name: estimated_delivery_at
      - name: delivery_at
      - name: status
        tests:
          - accepted_values:
              values: ['preparing', 'shipped', 'delivered']
  
  - name: stg_products 
    columns: 
      - name: product_id
        tests:
          - unique
          - not_null
      - name: name
      - name: price
        tests:
          - positive_values
      - name: inventory
        tests:
          - positive_values

  - name: stg_promos
    columns:
      - name: promo_id
        tests:
          - unique
          - not_null 
      - name: discount 
        tests:
          - positive_values
      - name: status 
        tests:
          - accepted_values:
              values: ['active', 'inactive']

  - name: stg_order_items
    columns:
      - name: order_id
        tests:
          - not_null 
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        tests:
          - not_null 
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: quantity
        tests:
          - positive_values

  - name: stg_users 
    columns:
      - name: user_id
        tests:
          - unique
          - not_null 
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: created_at
      - name: updated_at
      - name: address_id
        tests:
          - relationships:
              to: ref('stg_addresses')
              field: address_id
