version: 2

models:
  - name: fact_page_views
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: session_id
      - name: user_id
      - name: page_url
      - name: created_at_utc
      - name: event_type
      - name: order_id
      - name: product_id